from . import res_company
from . import res_partner
from . import res_city
from . import res_city_district
from . import l10n_latam_identification_type
from . import res_currency
from . import account_move
from . import account_journal
from . import account_tax
from . import amount_to_text_es
from . import odoopanama_org_cpe
from . import journal
from . import pa_payment_date
from . import product
from . import cpe_core_webpos
from . import odoopanama_cpe
from . import account_webpos
from . import pos_config
from . import pos_order
from . import pos_session
